package com.example.demo.bean;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Ccre
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private Float ccre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Chour
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private Integer chour;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cno
     *
     * @return the value of course.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cno
     *
     * @param cno the value for course.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cname
     *
     * @return the value of course.Cname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cname
     *
     * @param cname the value for course.Cname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Ccre
     *
     * @return the value of course.Ccre
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public Float getCcre() {
        return ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Ccre
     *
     * @param ccre the value for course.Ccre
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCcre(Float ccre) {
        this.ccre = ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Chour
     *
     * @return the value of course.Chour
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public Integer getChour() {
        return chour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Chour
     *
     * @param chour the value for course.Chour
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setChour(Integer chour) {
        this.chour = chour;
    }
}