package com.example.demo.bean;

public class SC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Sno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Cgrade
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private Float cgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Sno
     *
     * @return the value of sc.Sno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Sno
     *
     * @param sno the value for sc.Sno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Cno
     *
     * @return the value of sc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Cno
     *
     * @param cno the value for sc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Tno
     *
     * @return the value of sc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Tno
     *
     * @param tno the value for sc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Cgrade
     *
     * @return the value of sc.Cgrade
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public Float getCgrade() {
        return cgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Cgrade
     *
     * @param cgrade the value for sc.Cgrade
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCgrade(Float cgrade) {
        this.cgrade = cgrade;
    }
}