package com.example.demo.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sno
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Spassword
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String spassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sname
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Ssex
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String ssex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sdept
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String sdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sclass
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String sclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Splace
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String splace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Stel
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    private String stel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sno
     *
     * @return the value of student.Sno
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sno
     *
     * @param sno the value for student.Sno
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Spassword
     *
     * @return the value of student.Spassword
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Spassword
     *
     * @param spassword the value for student.Spassword
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sname
     *
     * @return the value of student.Sname
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sname
     *
     * @param sname the value for student.Sname
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Ssex
     *
     * @return the value of student.Ssex
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Ssex
     *
     * @param ssex the value for student.Ssex
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sdept
     *
     * @return the value of student.Sdept
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSdept() {
        return sdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sdept
     *
     * @param sdept the value for student.Sdept
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSdept(String sdept) {
        this.sdept = sdept == null ? null : sdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sclass
     *
     * @return the value of student.Sclass
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sclass
     *
     * @param sclass the value for student.Sclass
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSclass(String sclass) {
        this.sclass = sclass == null ? null : sclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Splace
     *
     * @return the value of student.Splace
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getSplace() {
        return splace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Splace
     *
     * @param splace the value for student.Splace
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setSplace(String splace) {
        this.splace = splace == null ? null : splace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Stel
     *
     * @return the value of student.Stel
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public String getStel() {
        return stel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Stel
     *
     * @param stel the value for student.Stel
     *
     * @mbggenerated Thu Jan 02 20:49:31 CST 2020
     */
    public void setStel(String stel) {
        this.stel = stel == null ? null : stel.trim();
    }
}