package com.example.demo.bean;

public class TC {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cterm
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String cterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cmaxnum
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private Integer cmaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cstate
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private Integer cstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Tno
     *
     * @return the value of tc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Tno
     *
     * @param tno the value for tc.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cno
     *
     * @return the value of tc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cno
     *
     * @param cno the value for tc.Cno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cterm
     *
     * @return the value of tc.Cterm
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getCterm() {
        return cterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cterm
     *
     * @param cterm the value for tc.Cterm
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCterm(String cterm) {
        this.cterm = cterm == null ? null : cterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cmaxnum
     *
     * @return the value of tc.Cmaxnum
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public Integer getCmaxnum() {
        return cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cmaxnum
     *
     * @param cmaxnum the value for tc.Cmaxnum
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCmaxnum(Integer cmaxnum) {
        this.cmaxnum = cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cstate
     *
     * @return the value of tc.Cstate
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public Integer getCstate() {
        return cstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cstate
     *
     * @param cstate the value for tc.Cstate
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setCstate(Integer cstate) {
        this.cstate = cstate;
    }
}