package com.example.demo.bean;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tpassword
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tsex
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tdept
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tpro
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tedu
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String tedu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Ttel
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    private String ttel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tno
     *
     * @return the value of teacher.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tno
     *
     * @param tno the value for teacher.Tno
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tpassword
     *
     * @return the value of teacher.Tpassword
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tpassword
     *
     * @param tpassword the value for teacher.Tpassword
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tname
     *
     * @return the value of teacher.Tname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tname
     *
     * @param tname the value for teacher.Tname
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tsex
     *
     * @return the value of teacher.Tsex
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTsex() {
        return tsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tsex
     *
     * @param tsex the value for teacher.Tsex
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTsex(String tsex) {
        this.tsex = tsex == null ? null : tsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tdept
     *
     * @return the value of teacher.Tdept
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTdept() {
        return tdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tdept
     *
     * @param tdept the value for teacher.Tdept
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTdept(String tdept) {
        this.tdept = tdept == null ? null : tdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tpro
     *
     * @return the value of teacher.Tpro
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTpro() {
        return tpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tpro
     *
     * @param tpro the value for teacher.Tpro
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTpro(String tpro) {
        this.tpro = tpro == null ? null : tpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tedu
     *
     * @return the value of teacher.Tedu
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTedu() {
        return tedu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tedu
     *
     * @param tedu the value for teacher.Tedu
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTedu(String tedu) {
        this.tedu = tedu == null ? null : tedu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Ttel
     *
     * @return the value of teacher.Ttel
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public String getTtel() {
        return ttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Ttel
     *
     * @param ttel the value for teacher.Ttel
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    public void setTtel(String ttel) {
        this.ttel = ttel == null ? null : ttel.trim();
    }
}