package com.example.demo.dao;

import com.example.demo.bean.tool.AllTsc;
import java.util.List;

public interface AllTscMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alltsc
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    int insert(AllTsc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alltsc
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    List<AllTsc> selectAll();

    List<AllTsc> selectByTno(String tno);
    List<AllTsc> selectByCno(String cno);
    List<AllTsc> selectBySno(String sno);
    List<AllTsc> selectByCterm(String cterm);
}