package com.example.demo.dao;

import com.example.demo.bean.tool.MyGrade;
import java.util.List;

public interface MyGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mygrade
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    int insert(MyGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mygrade
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    List<MyGrade> selectAll();

    List<MyGrade> selectByPrimaryKey(String sno);
}