package com.example.demo.dao;

import com.example.demo.bean.SC;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int deleteByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno, @Param("tno") String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int insert(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    SC selectByPrimaryKey(@Param("sno") String sno, @Param("cno") String cno, @Param("tno") String tno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    List<SC> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int updateByPrimaryKey(SC record);
}