package com.example.demo.dao;

import com.example.demo.bean.TC;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int deleteByPrimaryKey(@Param("tno") String tno, @Param("cno") String cno, @Param("cterm") String cterm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int insert(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    TC selectByPrimaryKey(@Param("tno") String tno, @Param("cno") String cno, @Param("cterm") String cterm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    List<TC> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Thu Jan 02 20:36:18 CST 2020
     */
    int updateByPrimaryKey(TC record);
}