package com.example.demo.dao;

import com.example.demo.bean.tool.TeaMyStu;
import java.util.List;

public interface TeaMyStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamystu
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    int insert(TeaMyStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teamystu
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    List<TeaMyStu> selectAll();
    List<TeaMyStu> selectByPrimaryKey(String tno);
}