package com.example.demo.bean.tool;

public class AllTsc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Sno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Spassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String spassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Sname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Ssex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String ssex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Sdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String sdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Sclass
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String sclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Splace
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String splace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Stel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String stel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Ccre
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private Float ccre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Chour
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private Integer chour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tpassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tsex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tdept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tpro
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tpro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Tedu
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String tedu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Ttel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String ttel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cterm
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private String cterm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cmaxnum
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private Integer cmaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cstate
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private Integer cstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alltsc.Cgrade
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    private Float cgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Sno
     *
     * @return the value of alltsc.Sno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Sno
     *
     * @param sno the value for alltsc.Sno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Spassword
     *
     * @return the value of alltsc.Spassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Spassword
     *
     * @param spassword the value for alltsc.Spassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword == null ? null : spassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Sname
     *
     * @return the value of alltsc.Sname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Sname
     *
     * @param sname the value for alltsc.Sname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Ssex
     *
     * @return the value of alltsc.Ssex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Ssex
     *
     * @param ssex the value for alltsc.Ssex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Sdept
     *
     * @return the value of alltsc.Sdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSdept() {
        return sdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Sdept
     *
     * @param sdept the value for alltsc.Sdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSdept(String sdept) {
        this.sdept = sdept == null ? null : sdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Sclass
     *
     * @return the value of alltsc.Sclass
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Sclass
     *
     * @param sclass the value for alltsc.Sclass
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSclass(String sclass) {
        this.sclass = sclass == null ? null : sclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Splace
     *
     * @return the value of alltsc.Splace
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getSplace() {
        return splace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Splace
     *
     * @param splace the value for alltsc.Splace
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setSplace(String splace) {
        this.splace = splace == null ? null : splace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Stel
     *
     * @return the value of alltsc.Stel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getStel() {
        return stel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Stel
     *
     * @param stel the value for alltsc.Stel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setStel(String stel) {
        this.stel = stel == null ? null : stel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cno
     *
     * @return the value of alltsc.Cno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cno
     *
     * @param cno the value for alltsc.Cno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cname
     *
     * @return the value of alltsc.Cname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cname
     *
     * @param cname the value for alltsc.Cname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Ccre
     *
     * @return the value of alltsc.Ccre
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public Float getCcre() {
        return ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Ccre
     *
     * @param ccre the value for alltsc.Ccre
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCcre(Float ccre) {
        this.ccre = ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Chour
     *
     * @return the value of alltsc.Chour
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public Integer getChour() {
        return chour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Chour
     *
     * @param chour the value for alltsc.Chour
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setChour(Integer chour) {
        this.chour = chour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tno
     *
     * @return the value of alltsc.Tno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tno
     *
     * @param tno the value for alltsc.Tno
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tpassword
     *
     * @return the value of alltsc.Tpassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tpassword
     *
     * @param tpassword the value for alltsc.Tpassword
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tname
     *
     * @return the value of alltsc.Tname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tname
     *
     * @param tname the value for alltsc.Tname
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tsex
     *
     * @return the value of alltsc.Tsex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTsex() {
        return tsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tsex
     *
     * @param tsex the value for alltsc.Tsex
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTsex(String tsex) {
        this.tsex = tsex == null ? null : tsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tdept
     *
     * @return the value of alltsc.Tdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTdept() {
        return tdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tdept
     *
     * @param tdept the value for alltsc.Tdept
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTdept(String tdept) {
        this.tdept = tdept == null ? null : tdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tpro
     *
     * @return the value of alltsc.Tpro
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTpro() {
        return tpro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tpro
     *
     * @param tpro the value for alltsc.Tpro
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTpro(String tpro) {
        this.tpro = tpro == null ? null : tpro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Tedu
     *
     * @return the value of alltsc.Tedu
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTedu() {
        return tedu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Tedu
     *
     * @param tedu the value for alltsc.Tedu
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTedu(String tedu) {
        this.tedu = tedu == null ? null : tedu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Ttel
     *
     * @return the value of alltsc.Ttel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getTtel() {
        return ttel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Ttel
     *
     * @param ttel the value for alltsc.Ttel
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setTtel(String ttel) {
        this.ttel = ttel == null ? null : ttel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cterm
     *
     * @return the value of alltsc.Cterm
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public String getCterm() {
        return cterm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cterm
     *
     * @param cterm the value for alltsc.Cterm
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCterm(String cterm) {
        this.cterm = cterm == null ? null : cterm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cmaxnum
     *
     * @return the value of alltsc.Cmaxnum
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public Integer getCmaxnum() {
        return cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cmaxnum
     *
     * @param cmaxnum the value for alltsc.Cmaxnum
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCmaxnum(Integer cmaxnum) {
        this.cmaxnum = cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cstate
     *
     * @return the value of alltsc.Cstate
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public Integer getCstate() {
        return cstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cstate
     *
     * @param cstate the value for alltsc.Cstate
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCstate(Integer cstate) {
        this.cstate = cstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alltsc.Cgrade
     *
     * @return the value of alltsc.Cgrade
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public Float getCgrade() {
        return cgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alltsc.Cgrade
     *
     * @param cgrade the value for alltsc.Cgrade
     *
     * @mbggenerated Sat Jan 04 21:32:14 CST 2020
     */
    public void setCgrade(Float cgrade) {
        this.cgrade = cgrade;
    }
}