package com.example.demo.bean.tool;

public class CourseChoose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Cno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Cname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Tno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Ccre
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private Float ccre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Chour
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private Integer chour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Cnumber
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private Long cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Cmaxnum
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private Integer cmaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coursechoose.Tname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Cno
     *
     * @return the value of coursechoose.Cno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Cno
     *
     * @param cno the value for coursechoose.Cno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Cname
     *
     * @return the value of coursechoose.Cname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Cname
     *
     * @param cname the value for coursechoose.Cname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Tno
     *
     * @return the value of coursechoose.Tno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Tno
     *
     * @param tno the value for coursechoose.Tno
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Ccre
     *
     * @return the value of coursechoose.Ccre
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public Float getCcre() {
        return ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Ccre
     *
     * @param ccre the value for coursechoose.Ccre
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setCcre(Float ccre) {
        this.ccre = ccre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Chour
     *
     * @return the value of coursechoose.Chour
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public Integer getChour() {
        return chour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Chour
     *
     * @param chour the value for coursechoose.Chour
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setChour(Integer chour) {
        this.chour = chour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Cnumber
     *
     * @return the value of coursechoose.Cnumber
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public Long getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Cnumber
     *
     * @param cnumber the value for coursechoose.Cnumber
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setCnumber(Long cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Cmaxnum
     *
     * @return the value of coursechoose.Cmaxnum
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public Integer getCmaxnum() {
        return cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Cmaxnum
     *
     * @param cmaxnum the value for coursechoose.Cmaxnum
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setCmaxnum(Integer cmaxnum) {
        this.cmaxnum = cmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coursechoose.Tname
     *
     * @return the value of coursechoose.Tname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coursechoose.Tname
     *
     * @param tname the value for coursechoose.Tname
     *
     * @mbggenerated Fri Jan 03 23:49:17 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}