package com.example.demo.bean.tool;

public class MyGrade {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Sno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Cno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Cname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Tno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Tname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mygrade.Cgrade
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    private Float cgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Sno
     *
     * @return the value of mygrade.Sno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Sno
     *
     * @param sno the value for mygrade.Sno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Cno
     *
     * @return the value of mygrade.Cno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Cno
     *
     * @param cno the value for mygrade.Cno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Cname
     *
     * @return the value of mygrade.Cname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Cname
     *
     * @param cname the value for mygrade.Cname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Tno
     *
     * @return the value of mygrade.Tno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Tno
     *
     * @param tno the value for mygrade.Tno
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Tname
     *
     * @return the value of mygrade.Tname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Tname
     *
     * @param tname the value for mygrade.Tname
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mygrade.Cgrade
     *
     * @return the value of mygrade.Cgrade
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public Float getCgrade() {
        return cgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mygrade.Cgrade
     *
     * @param cgrade the value for mygrade.Cgrade
     *
     * @mbggenerated Sat Jan 04 09:43:41 CST 2020
     */
    public void setCgrade(Float cgrade) {
        this.cgrade = cgrade;
    }
}