package com.example.demo.bean.tool;

public class TeaMyStu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Cno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String cno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Cname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Sno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String sno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Sname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Sclass
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String sclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Stel
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String stel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Tno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private String tno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teamystu.Cgrade
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    private Float cgrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Cno
     *
     * @return the value of teamystu.Cno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Cno
     *
     * @param cno the value for teamystu.Cno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Cname
     *
     * @return the value of teamystu.Cname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Cname
     *
     * @param cname the value for teamystu.Cname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Sno
     *
     * @return the value of teamystu.Sno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Sno
     *
     * @param sno the value for teamystu.Sno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Sname
     *
     * @return the value of teamystu.Sname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Sname
     *
     * @param sname the value for teamystu.Sname
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Sclass
     *
     * @return the value of teamystu.Sclass
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Sclass
     *
     * @param sclass the value for teamystu.Sclass
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setSclass(String sclass) {
        this.sclass = sclass == null ? null : sclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Stel
     *
     * @return the value of teamystu.Stel
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getStel() {
        return stel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Stel
     *
     * @param stel the value for teamystu.Stel
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setStel(String stel) {
        this.stel = stel == null ? null : stel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Tno
     *
     * @return the value of teamystu.Tno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Tno
     *
     * @param tno the value for teamystu.Tno
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teamystu.Cgrade
     *
     * @return the value of teamystu.Cgrade
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public Float getCgrade() {
        return cgrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teamystu.Cgrade
     *
     * @param cgrade the value for teamystu.Cgrade
     *
     * @mbggenerated Sat Jan 04 15:52:46 CST 2020
     */
    public void setCgrade(Float cgrade) {
        this.cgrade = cgrade;
    }
}